### ISSUE TITLE
Validation of multiple model types in a single module?

### ISSUE THREAD

**Issue by cocowalla** [felipeleusin/NancyFX.BeforeResponse#1]
`ValidatedModule` looks interesting, but I believe it can only allow validation of a single model type per module; that is, you would typically need 1 module for each verb/route combination, which sort of ruins 'cleanliness' of this otherwise elegant solution.

Is there some way to perform validation at the infrastructure level, such that it can work for multiple model types within a single module?

**Comment by felipeleusin** [comment]
I'm not sure how that would be possible. Since the upside of ValidatedModule is to have a typed Input property on the Module. At my company we use the one module per verb/route and it provides a very good approach for structuring in NancyFX.

If you want to bind and validated to different routes inside a single module you have to resort to writing an extension method that binds and validate and then throws but I'm not sure that's the best way to handle this.
